### ISSUE TITLE
Can't install Android Wear clock face from version 2.0

### ISSUE THREAD

**Issue by jpaana** [ItsCalebJones/SpaceLaunchNow-Android#102]
Installing the clock face to my LG G Watch R (Android Wear 2.7.0.x, Google Play Services 11.9.51, Android version 7.1.1) gives an error:
01-15 08:43:03.587   580   608 E PackageInstaller: Commit of session 2060580776 failed: Package /data/app/vmdl2060580776.tmp/me.calebjones.spacelaunchnow has no certificates at entry AndroidManifest.xml

Trying to manually adb install the apk gives similar error:
Failed to install android_wear_micro_apk.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Package /data/app/vmdl2066745846.tmp/base.apk has no certificates at entry AndroidManifest.xml]

The phone application installed fine and I could manually install the Wear apk from older 1.8 release.

**Comment by ItsCalebJones** [comment]
Thanks for the bug report! I'm working on a 2.0 standalone - might be a minute until its fixed.

**Comment by jpaana** [comment]
2.1.5 installed fine and all my nit picks seem to have been fixed nicely, thanks!
