### ISSUE TITLE
Android Wear clockface shows UTC not local time

### ISSUE THREAD

**Issue by jpaana** [ItsCalebJones/SpaceLaunchNow-Android#108]
Just updated to version 2.2.0.104 and the clock face now shows UTC time as both the local time and UTC time (so now it shows 15:45 in large numbers and below 15:45 UTC in smaller font) even though I'm at UTC+2. Previous versions worked fine.

**Comment by jpaana** [comment]
Noticed that in 12-hour clock mode is correct (shows 5:48 now), so only 24-hour mode has this issue.

**Comment by ItsCalebJones** [comment]
Interesting - thanks ill take a look.

**Comment by ItsCalebJones** [comment]
Fixed with commit 03e28049e9fa9d9058f1ed7c26e6d06a7591bd9a
