### ISSUE TITLE
Can no longer tap on notifications after latest updates 

### ISSUE THREAD

**Issue by Siedlerchr** [ItsCalebJones/SpaceLaunchNow-Android#109]
Hi, first of all thanks for the great app!
With the recent update 2.2.04 I can no longer tap on notifications to open the app.
The notification stay there and nothing happens
![screenshot_20180213-101213](https://user-images.githubusercontent.com/320228/36141808-7207b256-10a6-11e8-96b2-c25cfc48f4ca.png)

**Comment by ItsCalebJones** [comment]
Thanks for the report - i'll look into it.

**Comment by ItsCalebJones** [comment]
Could you try something for me? From Notification settings - click 'Send Test Notification' a few times and see if you can reproduce this?

**Comment by Siedlerchr** [comment]
I think I found the problem. If multiple notifications are combined into one and I then just tap on the condensed view it does not open. If I expand the notifications (image and details become visible) and then tap  on  one it works as expected.

I could reproduce this with the test notification

**Comment by ItsCalebJones** [comment]
I think it is as designed by Google. I can't find a method to set an action on bundle tap.
