### ISSUE TITLE
Can't load up Project

### ISSUE THREAD

**Issue by emmaunel** [ItsCalebJones/SpaceLaunchNow-Android#110]
I just want to ask how do you open your project in android studio because I am getting an error that says "Could not read Keystore.properties". 
Other error:

- Cannot resolve symbol 'GradleException'

- Cannot resolve symbol 'import org.moallemi.gradle.internal.VersionCodeType'

**Comment by ItsCalebJones** [comment]
Hello @emmaunel - create a file keystore.properties at the root of the project with the following content - there may be other excluded files and api keys that will need to be added. I will make a note to update the readme with steps to fully build the project.

```
storePassword=yourStorePassword
keyPassword=yourKeyPassword
keyAlias=yourAlias
storeFile=/full/path/to/keystore
```
