### ISSUE TITLE
Widget problem

### ISSUE THREAD

**Issue by Lubieerror** [ItsCalebJones/SpaceLaunchNow-Android#114]
Hello. I found a bug in widget.

When you set height to too little, it starts shows "X days Y days" (instead of "X days Y hours").
(Width don't matter)

### Bug:
![bug](https://i.imgur.com/JcXTnBT.jpg)

### Normal:
![normal](https://i.imgur.com/6GpV930.jpg)

_ Btw. great app, thx_ :smiley:

**Comment by ItsCalebJones** [comment]
Hey there!

This was fixed in 6c9b9270f95cabe4a2dea37bb79260c723360c7d will have the update out soon enough.

Thanks!
