### ISSUE TITLE
Calendar Sync Timezone issue

### ISSUE THREAD

**Issue by haffmans** [ItsCalebJones/SpaceLaunchNow-Android#129]
I use SpaceLaunchNow on Android 8 and sync events to a calendar. This calendar is synced by DavDroid to my CalDav server (Kolab-based). On all other devices, the times are shifted by the UTC offset of the time zone I live in (CEST - so that's UTC+2 at the moment).

Using iCal Import/Export 3.2 on Android to extract an ICS file of the calendar on the originating device, I get this event as an example:

~~~
BEGIN:VEVENT
DTSTART:20180909T032800Z
TRANSP:OPAQUE
DTEND;TZID=Europe/Amsterdam:20180909T092800
ORGANIZER:redacted@example.com
SUMMARY:Falcon 9 Block 5 | Telstar 18 VANTAGE
DESCRIPTION:Telstar 18 VANTAGE\, or Telstar 18V\, is a communications satellite built by Space Systems Loral for the canadian satellite operator Telesat. The satellite is to be provide coverage to the Asia Pacific region.\n\nWatch Live:\nhttp://www.spacex.com/webcast\n\n via Space Launch Now
LOCATION:Cape Canaveral\, FL\, USA
STATUS:TENTATIVE
DTSTAMP:20180904T200627Z
UID:2ac7209c-1d81-432e-bd8a-6182590de72e
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-PT30M
DESCRIPTION:
END:VALARM
END:VEVENT
~~~

What's noticable is the difference in timezone for the DTSTART and DTEND fields. It's possible the server misinterprets this difference due to a bug on their end, but the resulting event on the server:
- Has DTSTART converted to Europe/Amsterdam timezone (adds +2 hours), but stores that time as UTC (ends up as `DTSTART:20180909T052800Z`)
- Leaves the DTEND time as-is but interprets (and stores) it as UTC (`DTEND:20180909T092800Z`)

This calendar is the only one where I'm having this issue with; all other calendars which I have are synced consistently and don't break like this, regardless of the time zone of the events (but start and end are always in the same time zone).

**Comment by ItsCalebJones** [comment]
I'll look into this but I can't make any promises - just as a note there may be a better way to export the Launch calendar if your purpose is to import into a different calendar system. 

https://launchlibrary.net/1.4/calendar

**Comment by ItsCalebJones** [comment]
Closing this issue as wont fix for now.
