### ISSUE TITLE
Bug: Calendar launch event duplication

### ISSUE THREAD

**Issue by fkarg** [ItsCalebJones/SpaceLaunchNow-Android#164]
**Describe the bug**
I have multiple times the exact same launch event at the same time in my calendar. Up to eight the closer the launch.

**To Reproduce**
Steps to reproduce the behaviour:

Not sure. Activate 'calendar syn' for a start. Wait.

**Expected behaviour**
ONE entry of the soon-to-happen-launch.

**Screenshots**
![WhatsApp Image 2019-11-22 at 14 45 14](https://user-images.githubusercontent.com/9039899/69431016-1b439e00-0d37-11ea-95d5-dbd4901c5458.jpeg)

**Smartphone (please complete the following information):**
 - Device: Honor 10
 - OS: Android P 9.1
 - Version 3.2.2.44

**Comment by ItsCalebJones** [comment]
This should be fixed in 3.3.0 - reopen if you can reproduce.
