### ISSUE TITLE
Clicking does not seam to work correctly on the latest version that is on the play store.

### ISSUE THREAD

**Issue by timostrating** [ItsCalebJones/SpaceLaunchNow-Android#167]
**Describe the bug**
After the newest update clicking on some things does nothing until you miss click a little bit.
The newly added support us on patreon item is probably still active. My android skills are not that great so I personally did not find anything strange in the newly added code. 

**To Reproduce**
Open the app from google play on the newest update.
slide down the white patreon support banner. 
Open the menu.
Click on home.
Animation of clicking there plays.
App does not register click on home button.

**Screenshots**
https://imgur.com/a/oQuuTHQ

**Smartphone (please complete the following information):**
 - Device: oneplus 5
 - OS: OxygenOS 9.0.9 (newest)
 - Version 5 januarie 2020

**Comment by ItsCalebJones** [comment]
I've reverted that with cd2cc3ae74e8ab043cac85e9b8afe96f1c9624e5

**Comment by ItsCalebJones** [comment]
This has been fixed.
