### ISSUE TITLE
Duplicate calendar entries

### ISSUE THREAD

**Issue by fkarg** [ItsCalebJones/SpaceLaunchNow-Android#180]
I activated the feature to sync one of my calendars with upcoming rocket launches. For some reason though, some launch events are soon twice or thrice and sometimes fourteen times (yes, that actually happened) with the same date, time, title, description and tracking-id.

Honestly, I'm not sure how to reproduce - but it happened every time I tried using this feature. I'll happily provide any information necessary, since I don't think this is what is supposed to happen.

**Smartphone (please complete the following information):**
 - Device: Honor 10
 - OS: EMUI 10 / Android 10

**Comment by fkarg** [comment]
So I have two screenshots here with the calendar the app syncs to. The first is the 'duplicate view' in GCalToolkit, one of the few tools allowing for duplicate removal of google calendar events, the other is how it looks like in the browser.

I'll gladly provide you with any information you need to figure this out.

![2021-04-13-160459_1920x2160_scrot](https://user-images.githubusercontent.com/9039899/114568252-44d6cf80-9c74-11eb-99a7-0ca1dc1a7dd6.png)
![2021-04-13-160534_1920x2160_scrot](https://user-images.githubusercontent.com/9039899/114568259-456f6600-9c74-11eb-8eb7-e96c373f09c1.png)

**Comment by ItsCalebJones** [comment]
Thanks for the details - i'll take a look at it, i'm honestly sort of leaning towards providing the iCal link to supporters rather then this sync code. It's more work as someone would need to take the link and import it in the right place but this code has been a nightmare to maintain over the years.

**Comment by fkarg** [comment]
I can imagine :sweat_smile: Thanks for looking into this!

Also: here's a link to the calendar directly: https://calendar.google.com/calendar/embed?src=gv9lqpuibgn392nhrf593btcbc%40group.calendar.google.com&ctz=Europe%2FBerlin

I removed duplicates earlier, but I'll let them pile up, maybe that'll help? A number of duplicates should be there again tomorrow or in a few days at most.
