### ISSUE TITLE
Filters not working

### ISSUE THREAD

**Issue by Trigant** [ItsCalebJones/SpaceLaunchNow-Android#193]
**Describe the bug**
A selection of filters does not have any effect to the list of upcoming starts. For example, if I deselect SpaceX it doesn't hide its launches.

**To Reproduce**
1. Go to Filters
2. Deselct Spacex
3. Click on apply
4. List reloads and shows the exact same things like before

**Expected behavior**
A shorter list of upcoming starts as before.

**Screenshots**
Not availabe

**Smartphone (please complete the following information):**
 - Device: Fairphone 3+
 - OS: LineageOS
 - Version: 19.1

**Additional context**
N/A

**Comment by ItsCalebJones** [comment]
This is working as expected - read the info for Strict Matching - unless that is on the filters act like an OR... meaning if the launch is from the Cape you will still get ALL launches from the Cape unless you turn on Strict Matching.
