### ISSUE TITLE
Android Wear 24h-mode hour display should be 0-23, not 1-24

### ISSUE THREAD

**Issue by jpaana** [ItsCalebJones/SpaceLaunchNow-Android#98]
Midnight is supposed to be 00:00, but currently the watch displays 24:00. Changing line 353 in SpaceLaunchWatchFace.java from:
            SimpleDateFormat twentyFourHourMode = new SimpleDateFormat("kk:mm");
to
            SimpleDateFormat twentyFourHourMode = new SimpleDateFormat("HH:mm");

fixes this.

**Comment by ItsCalebJones** [comment]
Releasing in 2.0.0
