### ISSUE TITLE
Android Wear date display is not locale friendly

### ISSUE THREAD

**Issue by jpaana** [ItsCalebJones/SpaceLaunchNow-Android#99]
Currently the date format is fixed to English date format and displays rather weird combinations when using some other locale, for example my Finnish locale displays today: "keskiviikkona, joulukuuta 20th" which probably should be something like "keskiviikkona, 20. joulukuuta" though even that is a bit unnatural. Unfortunately Android doesn't seem to have a suitable locale sensitive date format for this case so it would have to be somehow deduced from the DateFormat.FULL string or using android.text.format.DateFormat.getBestDateTimePattern() call might also work.

**Comment by ItsCalebJones** [comment]
You would think this many years into Android development this would be a solved issue. =/ 

Thanks for bringing it up - I will look into it but not sure if it will make it into 2.0.0

**Comment by jpaana** [comment]
This seems to be improved in 2.1.5 as well, at least the Finnish locale seems quite sensible.
